import type { AppSettings, SegmentType } from "./types";

export const segmentTypes: SegmentType[] = [
  "narration",
  "dialogue",
  "inner_monologue",
  "sound_cue",
  "transition",
  "timing_anchor",
  "unknown",
];

export const ageStages = ["childhood", "teenager", "young_adult", "adult", "middle_aged", "elderly"];

export const text = {
  ready: "就绪",
  done: "完成",
  noProject: "未打开项目",
  createProjectDialog: "创建 Xiic Voice Studio 项目文件夹",
  openProjectDialog: "打开项目文件夹",
  sourceFilter: "稿件来源",
  createProject: "创建项目",
  openingProject: "打开项目",
  importingSource: "导入稿件",
  markingChapter: "标注章节",
  savingSegment: "保存分段",
  assigningVoice: "分配声音",
  savingApiKey: "保存 API Key",
  deletingApiKey: "删除 API Key",
  generatingTts: "生成语音",
  loadingAudio: "加载音频",
  uploadingAudio: "上传音频",
  approvingAudio: "审听通过",
  rejectingAudio: "标记返修",
  addingReviewIssue: "添加审听问题",
  cancelJob: "取消任务",
  retryJob: "重试任务",
  queued: "已加入任务队列",
  openAudioFolder: "打开音频目录",
  exportingEpisode: "导出整集",
  checkingProduction: "发布检查",
  checkingFfmpeg: "检查 FFmpeg",
  exportVoiceScript: "导出脚本",
  exportSegmentAudio: "导出分段音频",
  exportedEpisode: "整集已导出",
  open: "打开",
  import: "导入",
  mark: "标注",
  generate: "生成",
  activeTasks: "个任务",
  project: "项目",
  author: "作者",
  createLocalProject: "创建本地项目",
  chapters: "章节",
  emptyChapters: "创建项目并导入 TXT/DOCX 后开始制作。",
  providers: "服务配置",
  llmBaseUrl: "LLM 基础地址",
  llmModel: "LLM 模型",
  llmApiKey: "LLM API Key",
  ttsProvider: "TTS 供应商",
  ttsApiKey: "TTS API Key",
  saveApiKey: "保存密钥",
  deleteApiKey: "删除密钥",
  apiKeySaved: "密钥已保存到系统 Keychain",
  noApiKeySaved: "密钥未保存",
  ttsEndpoint: "TTS Base URL",
  ttsModel: "TTS 模型",
  ttsVoiceId: "默认音色 / VoiceDesign 描述",
  ttsStylePrompt: "声音设计提示",
  ffmpegPath: "FFmpeg 路径",
  episodeFormat: "整集格式",
  projectCover: "项目封面",
  chooseCover: "选择封面",
  coverSaved: "封面已保存到项目",
  checkingAssets: "检查项目资产",
  backingUpProject: "备份项目",
  assetsValid: "项目资产完整",
  backupReady: "项目备份已生成",
  checkFfmpeg: "检查 FFmpeg",
  loadingVoices: "加载音色",
  loadVoices: "加载音色",
  voiceCatalogLoaded: "音色列表已加载",
  testingTts: "测试 TTS",
  testTts: "测试 TTS",
  ttsTestReady: "TTS 测试音频已生成",
  openTtsTestAudio: "打开测试音频",
  scriptWorkspace: "脚本工作台",
  localWorkbench: "本地优先制作工作台",
  segmentUnit: "个分段",
  characterUnit: "个角色",
  script: "脚本",
  segmentAudio: "分段音频",
  episode: "整集",
  package: "制作包",
  productionCheck: "发布检查",
  index: "#",
  type: "类型",
  speaker: "说话人",
  content: "文本",
  status: "状态",
  tools: "操作",
  narrator: "旁白",
  playLatestAudio: "播放最新音频",
  uploadSegmentAudio: "上传人工音频",
  regenerateSegment: "重新生成分段",
  emptySegments: "导入并标注章节后，会在这里生成可编辑的制作分段。",
  characters: "角色",
  noAliases: "无别名",
  assignVoice: "分配声音",
  mergeCharacters: "合并角色",
  sourceCharacter: "来源角色",
  targetCharacter: "目标角色",
  emptyCharacters: "标注出角色台词后会在这里显示角色。",
  voices: "声音",
  addNarratorVoice: "添加旁白声音",
  review: "审听",
  addReviewNote: "添加审听备注",
  approveAudio: "通过",
  rejectAudio: "返修",
  queue: "任务队列",
  publishReady: "可发布",
  publishBlocked: "需处理",
  readiness: "发布状态",
  noSegment: "未选择分段",
  reviewNote: "需要检查节奏或表演",
  narratorVoice: "旁白声音",
  adultVoice: "成年声音",
  mimoVoice: "Mimo 声音",
};

export const segmentTypeLabels: Record<SegmentType, string> = {
  narration: "旁白",
  dialogue: "台词",
  inner_monologue: "内心独白",
  sound_cue: "音效",
  transition: "转场",
  timing_anchor: "时间点",
  unknown: "未知",
};

export const ageStageLabels: Record<string, string> = {
  childhood: "童年",
  teenager: "少年",
  young_adult: "青年",
  adult: "成年",
  middle_aged: "中年",
  elderly: "老年",
};

export const reviewIssueLabels: Record<string, string> = {
  performance: "表演",
  pronunciation: "发音",
  timing: "节奏",
  audio_quality: "音质",
  human_note: "人工备注",
};

export const statusLabels: Record<string, string> = {
  imported: "已导入",
  marked: "已标注",
  missing: "缺失",
  generated: "已生成",
  uploaded: "已上传",
  unreviewed: "未审听",
  approved: "已通过",
  rejected: "需返修",
  pending: "等待中",
  running: "运行中",
  succeeded: "已完成",
  failed: "失败",
  canceled: "已取消",
  active: "进行中",
};

export const jobTypeLabels: Record<string, string> = {
  mark_chapter: "章节标注",
  tts_batch: "语音生成",
  import_source: "稿件导入",
  export_episode: "整集导出",
};

export const ttsProviderLabels: Record<string, string> = {
  mimo: "Mimo",
  mock: "Mock 演示",
  "aliyun-bailian": "阿里百炼",
};

export const providerDefaults: Record<
  string,
  { endpoint: string; model: string; voiceId: string; stylePrompt: string }
> = {
  mimo: {
    endpoint: "https://api.xiaomimimo.com/v1",
    model: "mimo-v2.5-tts-voicedesign",
    voiceId: "温柔、清澈、适合长篇有声书旁白的成年女声",
    stylePrompt: "温柔、清澈、自然，适合长篇有声读物旁白；语速稳定，情绪克制但有画面感。",
  },
  mock: {
    endpoint: "",
    model: "mock",
    voiceId: "mock-female-narrator",
    stylePrompt: "narration",
  },
  "aliyun-bailian": {
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation",
    model: "cosyvoice-v2",
    voiceId: "longxiaochun",
    stylePrompt: "narration",
  },
};

export const defaultAppSettings: AppSettings = {
  schemaVersion: 1,
  llm: { baseUrl: "https://api.openai.com/v1", model: "gpt-4.1-mini" },
  tts: {
    provider: "mimo",
    endpoint: providerDefaults.mimo.endpoint,
    model: providerDefaults.mimo.model,
    voiceId: providerDefaults.mimo.voiceId,
    stylePrompt: providerDefaults.mimo.stylePrompt,
  },
  audio: { ffmpegPath: "", episodeFormat: "m4b" },
};

export const desktopRuntimeMessage =
  "当前为浏览器预览模式。连接测试、密钥管理和本地文件操作需要在 Xiic Voice Studio 桌面应用中执行。";
